name: pharos-ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node + pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Enable corepack
        run: corepack enable

      - name: Install deps (pnpm)
        # avoids frozen-lockfile mismatch noise
        run: pnpm install --no-frozen-lockfile

      - name: Build DS package (if present)
        run: pnpm -F @pharos/design-system build || echo "no DS build step"

      - name: Build web app
        run: pnpm -F pharos-web build
