name: pharos-ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pharos-ci:
    name: pharos-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # install all workspaces deps at root
      - run: npm ci

      # install browsers in the web workspace (where Playwright is declared)
      - name: Install Playwright Browsers
        working-directory: apps/web
        run: npx playwright install --with-deps

      # optional lint
      - run: npm run lint --if-present

      # run E2E from the web workspace as well
      - name: Run E2E
        working-directory: apps/web
        env:
          NEXT_TELEMETRY_DISABLED: 1
          CI: true
        run: npm run test:e2e -- --reporter=dot --max-failures=1
