name: pharos-ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pharos-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node + pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Enable corepack
        run: corepack enable

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        working-directory: apps/web
        run: npx playwright install --with-deps chromium

      - name: Run E2E tests
        working-directory: apps/web
        env:
          NEXT_TELEMETRY_DISABLED: "1"
          CI: "true"
        run: pnpm test:e2e -- --reporter=dot --max-failures=1 --workers=1

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: apps/web/playwright-report
          if-no-files-found: ignore
