name: pharos-ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run tokens:build
      - run: npm run lint:tokens
      - run: npx playwright install --with-deps
      - run: npm run test:e2e


