name: pharos-ci

on:
  pull_request:
    branches: [main]   # runs on PRs to main
  push:
    branches: [main]   # also runs on merges to main

jobs:
  pharos-ci:
    name: pharos-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      # Optional: lint if you have it
      - run: npm run lint --if-present
      # Your real gate: the web E2E (no FIGMA secrets needed)
      - run: npm run --workspace apps/web test:e2e -- --reporter=dot --max-failures=1
