name: pharos-ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pharos-ci:
    name: pharos-ci
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node + pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Enable corepack
        run: corepack enable

      - name: Install deps (pnpm)
        run: pnpm install --no-frozen-lockfile

      # Build DS if it exists (harmless if noop)
      - name: Build DS package (if present)
        run: pnpm -F @pharos/design-system build || echo "no DS build step"

      - name: Install Playwright browsers (chromium only)
        working-directory: apps/web
        run: npx playwright install --with-deps chromium

      - name: Lint (if present)
        run: pnpm -F pharos-web lint --if-present

      - name: Run E2E
        working-directory: apps/web
        env:
          NEXT_TELEMETRY_DISABLED: 1
          CI: true
        run: |
          npx playwright --version
          pnpm test:e2e -- --reporter=dot --max-failures=1 --workers=1

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: apps/web/playwright-report
          if-no-files-found: ignore
