name: pharos-ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pharos-ci:
    name: pharos-ci
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (with pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # Make pnpm available; if packageManager is missing, still prepare it.
      - name: Enable Corepack + pin pnpm
        run: |
          corepack enable
          if ! node -p "require('./package.json').packageManager?.startsWith('pnpm@')"; then
            echo "No packageManager field; preparing pnpm@9.12.0"
            corepack prepare pnpm@9.12.0 --activate
          fi
          pnpm --version
          node -v

      # Install from the workspace root; avoid frozen lockfile insta-fail
      - name: Install deps (pnpm)
        run: pnpm install --no-frozen-lockfile

      # Best-effort DS build (don't fail CI if missing/no-op)
      - name: Build DS package (if present)
        run: pnpm --filter ./packages/pharos-design-system... run -r build || echo "no DS build step"

      # Always build the web app by path (works regardless of package name)
      - name: Build web app
        run: pnpm --filter ./apps/web... run build
